services:
  ds1:
    image: datastore
    hostname: dstore1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/madalv/Univer/pr/distributed-datastore/config1:/app/config1"
    ports:
      - "8070:8070"
      - "8071:8071"
      - "8072:8072"
    networks:
      - cluster
  ds2:
    image: datastore
    hostname: dstore2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/madalv/Univer/pr/distributed-datastore/config2:/app/config1"
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    networks:
      - cluster
  ds3:
    image: datastore
    hostname: dstore3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/madalv/Univer/pr/distributed-datastore/config3:/app/config1"
    ports:
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
    networks:
      - cluster
networks:
  cluster:
    name: cluster